{{- if eq .Values.nacos.storage.type "mysql"}}
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Values.nacos.storage.db.host }}
  namespace: {{ .Values.namespace }}
  labels:
    name: mysql

spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: {{ .Values.nacos.storage.db.host }}
        image: nacos/nacos-mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "nacos_devtest"
        - name: MYSQL_USER
          value: {{ .Values.nacos.storage.db.username }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.nacos.storage.db.password }}
      volumes:
      - name: mysql-data
{{/*        hostPath:*/}}
{{/*          path: /var/lib/mysql*/}}
 {{- end }}

---
{{- if eq .Values.nacos.storage.type "mysql"}}
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
  labels:
    name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql
 {{- end }}